In [1]:
import numpy as np
import pandas as pd
import sklearn.model_selection
from sklearn.model_selection import KFold

In [2]:
dataset = pd.read_csv('/home/test-machine/training.csv')
dataset.describe()

APL  AvgPktPerSec           IAT     NumForward       BytesEx  \
count  356156.000000  3.561560e+05  3.561560e+05  356156.000000  3.561560e+05   
mean      126.303021  1.857459e+04  4.157275e+06      11.394142  1.288425e+04   
std       220.298208  1.092119e+05  4.019257e+07     135.034150  2.623137e+05   
min         0.000000 -4.510000e-05 -2.220000e+10       1.000000  0.000000e+00   
25%         0.000000  6.929253e-01  1.007800e+04       2.000000  0.000000e+00   
50%        19.000000  1.245335e+01  1.236720e+05       3.000000  7.600000e+01   
75%       131.000000  1.867060e+02  1.782490e+06       6.000000  6.540000e+02   
max      1455.000000  2.000000e+06  1.200000e+08   15016.000000  4.090536e+07   

         BitsPerSec     NumPackets      StdDevLen      Duration  \
count  3.561560e+05  356156.000000  356156.000000  3.561560e+05   
mean   2.372350e+06      26.087299      22.675727  1.138906e+07   
std    4.009150e+07     358.542367      74.843656  2.684556e+07   
min    0.000000e+00       2.000000       0.000000 -3.000000e+00   
25%    0.000000e+00       2.000000       0.000000  1.374225e+04   
50%    1.246165e+02       3.000000       0.000000  4.931940e+05   
75%    2.165235e+04       7.000000      21.000000  9.011137e+06   
max    2.312000e+09   44710.000000    1397.840000  1.200000e+08   

                IOPR          isBot  
count  356156.000000  356156.000000  
mean        0.670665       0.607245  
std         0.740330       0.488364  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.500000       1.000000  
75%         1.000000       1.000000  
max        75.000000       1.000000

In [3]:
features = dataset[['APL','AvgPktPerSec','IAT','NumForward','BytesEx','BitsPerSec','NumPackets','StdDevLen','Duration','IOPR']]
labels = np.asarray(dataset.isBot)

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(labels)

# apply encoding to labels
labels = le.transform(labels)

In [5]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5,shuffle=True)

In [6]:
result1 = next(kf.split(features), None)
print (result1)
labels1 = labels[result1[0]]
train1 = features.iloc[result1[0]]

(array([     0,      1,      2, ..., 356151, 356152, 356154]), array([     8,     15,     21, ..., 356142, 356153, 356155]))


In [7]:
result1 = next(kf.split(features), None)
print (result1)
labels2 = labels[result1[0]]
train2 = features.iloc[result1[0]]

(array([     0,      1,      2, ..., 356152, 356153, 356154]), array([     3,      4,     24, ..., 356147, 356150, 356155]))


In [8]:
result1 = next(kf.split(features), None)
print (result1)
labels3 = labels[result1[0]]
train3 = features.iloc[result1[0]]

(array([     0,      1,      2, ..., 356152, 356153, 356155]), array([    12,     14,     15, ..., 356136, 356147, 356154]))


In [9]:
result1 = next(kf.split(features), None)
print (result1)
labels4 = labels[result1[0]]
train4 = features.iloc[result1[0]]

(array([     1,      2,      4, ..., 356152, 356153, 356155]), array([     0,      3,     10, ..., 356146, 356151, 356154]))


In [10]:
result1 = next(kf.split(features), None)
print (result1)
labels5 = labels[result1[0]]
train5 = features.iloc[result1[0]]

(array([     1,      3,      6, ..., 356153, 356154, 356155]), array([     0,      2,      4, ..., 356138, 356139, 356141]))


In [11]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn import ensemble
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestClassifier

In [12]:
clf1 = RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
clf1.fit(train1, labels1)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [13]:
clf2 = RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
clf2.fit(train2, labels2)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [14]:
clf3 = RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
clf3.fit(train3, labels3)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [15]:
clf4 = RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
clf4.fit(train4, labels4)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [16]:
clf5 = RandomForestClassifier(n_estimators=10, max_depth=None,min_samples_split=2, random_state=0)
clf5.fit(train5, labels5)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [17]:
dataset1 = pd.read_csv('/home/test-machine/testing.csv')
dataset1.describe()

APL  AvgPktPerSec           IAT     NumForward       BytesEx  \
count  309187.000000  3.091870e+05  3.091870e+05  309187.000000  3.091870e+05   
mean       56.756410  1.811844e+04 -4.119085e+07       9.093312  5.828903e+03   
std       133.963459  9.937677e+04  4.061827e+09     436.040674  3.991983e+05   
min         0.000000 -2.800050e+00 -1.820000e+12       1.000000  0.000000e+00   
25%         0.000000  6.657120e-01  3.204250e+03       1.000000  0.000000e+00   
50%        13.600000  1.434940e+01  1.001330e+05       3.000000  6.000000e+01   
75%        52.000000  5.000000e+02  1.802610e+06       6.000000  1.810000e+02   
max      2199.540000  2.000000e+06  1.200000e+08  178670.000000  1.420908e+08   

         BitsPerSec     NumPackets      StdDevLen      Duration  \
count  3.091870e+05  309187.000000  309187.000000  3.091870e+05   
mean   6.099850e+05      15.842497      19.468980  1.599731e+07   
std    1.063099e+07     648.409639      72.480734  3.426382e+07   
min   -2.479040e+04       2.000000       0.000000 -7.947514e+08   
25%    0.000000e+00       2.000000       0.000000  4.000000e+03   
50%    3.600510e+01       3.000000       0.000000  3.211740e+05   
75%    1.612905e+04       8.000000       0.000000  9.000888e+06   
max    1.440000e+09  203772.000000    3451.770000  1.200000e+08   

                IOPR          isBot  
count  309187.000000  309187.000000  
mean        0.651805       0.625321  
std         0.676882       0.484041  
min         0.000000       0.000000  
25%         0.000000       0.000000  
50%         0.764706       1.000000  
75%         1.000000       1.000000  
max       115.000000       1.000000

In [18]:
features11 = dataset1[['APL','AvgPktPerSec','IAT','NumForward','BytesEx','BitsPerSec','NumPackets','StdDevLen','Duration','IOPR']]
labels11 = np.asarray(dataset1.isBot)
le1 = LabelEncoder()

le1.fit(labels11)

# apply encoding to labels
labels11 = le.transform(labels11)

In [19]:
labels11.shape

(309187,)

In [20]:
import time
start_time = time.time()
final_labels11 = clf1.predict(features11)
end_time = time.time()
print ('end-time ',end_time)
print ('start_timee ',start_time)
print ('end-time - start_time ',(end_time - start_time)/309187)

end-time  1527629159.0367293
start_timee  1527629158.421575
end-time - start_time  1.989586452074058e-06


In [21]:
start_time = time.time()
final_labels21 = clf2.predict(features11)
end_time = time.time()
print ('end-time ',end_time)
print ('start_timee ',start_time)
print ('end-time - start_time ',(end_time - start_time)/309187)

end-time  1527629161.1170826
start_timee  1527629160.5101435
end-time - start_time  1.963016159726377e-06


In [22]:
start_time = time.time()
final_labels31 = clf3.predict(features11)
end_time = time.time()
print ('end-time ',end_time)
print ('start_timee ',start_time)
print ('end-time - start_time ',(end_time - start_time)/309187)

end-time  1527629164.9565518
start_timee  1527629164.3674662
end-time - start_time  1.905272792576845e-06


In [23]:
start_time = time.time()
final_labels41 = clf4.predict(features11)
end_time = time.time()
print ('end-time ',end_time)
print ('start_timee ',start_time)
print ('end-time - start_time ',(end_time - start_time)/309187)

end-time  1527629166.5280023
start_timee  1527629165.9181857
end-time - start_time  1.972322740634296e-06


In [24]:
start_time = time.time()
final_labels51 = clf5.predict(features11)
end_time = time.time()
print ('end-time ',end_time)
print ('start_timee ',start_time)
print ('end-time - start_time ',(end_time - start_time)/309187)

end-time  1527629169.4755735
start_timee  1527629168.8497925
end-time - start_time  2.0239565675954575e-06


In [25]:
final_labelss = []
final_labelss.append(final_labels11)
final_labelss.append(final_labels21)
final_labelss.append(final_labels31)
final_labelss.append(final_labels41)
final_labelss.append(final_labels51)

In [26]:
final = []
for i in range(len(labels11)):
    count = 0
    for j in range(5):
        if final_labelss[j][i] ==1:
            count += 1
    if count>2:
        final.append(1)
    else:
        final.append(0)

In [27]:
from sklearn.metrics import confusion_matrix
confusion_matrix(labels11, final)

array([[ 80852,  34994],
       [106870,  86471]])

In [28]:
from sklearn.metrics import classification_report
print (classification_report(labels11,final))

             precision    recall  f1-score   support

          0       0.43      0.70      0.53    115846
          1       0.71      0.45      0.55    193341

avg / total       0.61      0.54      0.54    309187



In [29]:
from sklearn.metrics import accuracy_score
print (accuracy_score(labels11,final))

0.5411708771714205
